try
Peipay1030/HelloReact pull request #27
Opened 2024-02-13 15:12 UTC by Peipay1030

-.. . -.- .. .- -   .-.. .   -- --- .-. ... .   ..-. . .-.. .-.. .-.-.-

2024-02-13 15:52 UTC, torikatsupg requested changes
方向性はあってる！コメントしたところ直してみてほしい！

（モールス信号？解読できんかった...）

2024-02-13 15:57 UTC, Peipay1030 commented on src/App.tsx
削除！

2024-02-13 15:58 UTC, Peipay1030 commented on src/App.tsx
> +  uuid: string;
直した！

2024-02-14 14:22 UTC, torikatsupg commented
- #4

2024-02-14 14:27 UTC, Peipay1030 commented
これでどう？

2024-02-14 14:37 UTC, merged